### ISSUE TITLE
Allow sub messages

### ISSUE THREAD

**Issue by confuser** [Frostcast/BukkitPluginUtil#3]
E.g
```java
Message.get("hello.world.foo.bar");
```

```yaml
hello:
  world:
    foo:
      bar: 'Hello world, I have some foo bar'
```
